upstream backoffice {
    server backoffice:8000;
}

server {
    listen 80;
    server_name localhost;

    client_max_body_size 20M;

    # Custom error page for 502 Bad Gateway
    error_page 502 /502.html;
    location /502.html {
        root /etc/nginx/conf.d; # This is where the 502.html will be mounted
        internal;
    }

    location / {
        proxy_pass http://backoffice;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }

    location /static/ {
        proxy_pass http://backoffice;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://backoffice;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://backoffice;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
