# Generated by Django 5.0.1 on 2026-02-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EtlError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_type", models.CharField(max_length=50)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("json_file", models.CharField(blank=True, max_length=255, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ETL Error",
                "verbose_name_plural": "ETL Errors",
                "db_table": "etl_errors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EtlRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_type", models.CharField(max_length=50)),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("staging_count", models.IntegerField(default=0)),
                ("inserted_count", models.IntegerField(default=0)),
                ("updated_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("staging_completed_at", models.DateTimeField(blank=True, null=True)),
                ("upsert_completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ETL Run",
                "verbose_name_plural": "ETL Runs",
                "db_table": "etl_runs",
                "ordering": ["-started_at"],
            },
        ),
    ]
