# Auto-provisioning datasource Grafana: Prometheus, Loki, Tempo
apiVersion: 1

deleteDatasources:
  - name: Jaeger
    orgId: 1

datasources:
  # Metriche
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  # Log — con link derivato ai traces via Tempo
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - datasourceUid: P214B5B846CF3925F
          matcherRegex: '"otelTraceID":\s*"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'

  # Traces
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: true
      tracesToMetrics:
        datasourceUid: prometheus
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
