apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-https
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grafana.oci.santocaruso.eu`)
      kind: Rule
      middlewares:
        - name: google-auth
          namespace: traefik
      services:
        - name: grafana
          port: 80
  tls:
    certResolver: letsencrypt
