apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - prometheus-ingressroute.yml
  - alertmanager-ingressroute.yml
  - loki-ingressroute.yml
  - dashboard-ingressroute.yml
  - grafana-ingressroute.yml
