resources:
  limits:
    cpu: 100m
    memory: 64Mi
  requests:
    cpu: 10m
    memory: 32Mi
config:
  clients:
    - url: http://loki:3100/loki/api/v1/push
  snippets:
    pipelineStages:
      - cri: {}
      - match:
          selector: '{namespace="events", container=~"backoffice|celery-worker|celery-beat"}'
          stages:
            - json:
                expressions:
                  level: level
                  logger: logger
            - labels:
                level:
                logger:
