tempo:
  storage:
    trace:
      backend: local
      local:
        path: /var/tempo/traces
  retention: 168h
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  metricsGenerator:
    enabled: true
    remoteWriteUrl: http://prometheus-server.monitoring.svc:80/api/v1/write

persistence:
  enabled: true
  size: 2Gi

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

nodeSelector:
  workload: heavy
