apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
  labels:
    app: airflow
data:
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags/repo/infrastructures/services/airflow/dags"
  AIRFLOW__WEBSERVER__BASE_URL: "https://airflow.oci.santocaruso.eu"
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"
  AIRFLOW__WEBSERVER__WORKERS: "1"
  AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: "300"
  AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "300"
  AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "30"
  AIRFLOW__CORE__PARALLELISM: "4"
  AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: "2"
