# Generated by Django 5.0.1 on 2026-03-22 12:09

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appartenenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Appartenenza',
                'verbose_name_plural': 'Appartenenze',
                'db_table': 'comuni_italiani"."appartenenze',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codice_istat', models.CharField(max_length=10, unique=True)),
                ('codice_catastale', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('popolazione', models.IntegerField(blank=True, null=True)),
                ('superficie_kmq', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('densita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cap', models.CharField(blank=True, max_length=10, null=True)),
                ('prefisso_telefonico', models.CharField(blank=True, max_length=10, null=True)),
                ('patrono', models.CharField(blank=True, max_length=200, null=True)),
                ('festa_patronale', models.CharField(blank=True, max_length=100, null=True)),
                ('demonimo', models.CharField(blank=True, max_length=200, null=True)),
                ('etimologia', models.TextField(blank=True, null=True)),
                ('il_comune_e', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'db_table': 'comuni_italiani"."comuni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(blank=True, max_length=5, null=True)),
                ('codice_istat', models.CharField(max_length=5, unique=True)),
                ('zona', models.CharField(blank=True, max_length=100, null=True)),
                ('popolazione', models.IntegerField(blank=True, null=True)),
                ('popolazione_maschi', models.IntegerField(blank=True, null=True)),
                ('popolazione_femmine', models.IntegerField(blank=True, null=True)),
                ('superficie_kmq', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('densita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_comuni', models.SmallIntegerField(blank=True, null=True)),
                ('capoluogo', models.CharField(blank=True, max_length=100, null=True)),
                ('iso_3166_2', models.CharField(blank=True, max_length=10, null=True)),
                ('nuts', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'db_table': 'comuni_italiani"."province',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codice_istat', models.CharField(max_length=5, unique=True)),
                ('popolazione', models.IntegerField(blank=True, null=True)),
                ('popolazione_maschi', models.IntegerField(blank=True, null=True)),
                ('popolazione_femmine', models.IntegerField(blank=True, null=True)),
                ('superficie_kmq', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('densita', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_province', models.SmallIntegerField(blank=True, null=True)),
                ('num_comuni', models.SmallIntegerField(blank=True, null=True)),
                ('capoluogo', models.CharField(blank=True, max_length=100, null=True)),
                ('iso_3166_2', models.CharField(blank=True, max_length=10, null=True)),
                ('nuts', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'db_table': 'comuni_italiani"."regioni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ComuneAppartenenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('ordine', models.SmallIntegerField(default=0)),
                ('appartenenza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuni_appartenenza', to='comuni_italiani.appartenenza')),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appartenenze', to='comuni_italiani.comune')),
            ],
            options={
                'verbose_name': 'Appartenenza',
                'verbose_name_plural': 'Appartenenze',
                'db_table': 'comuni_italiani"."comune_appartenenze',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ComuneCittadinoIllustre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('ordine', models.SmallIntegerField(default=0)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cittadini_illustri', to='comuni_italiani.comune')),
            ],
            options={
                'verbose_name': 'Cittadino illustre',
                'verbose_name_plural': 'Cittadini illustri',
                'db_table': 'comuni_italiani"."comune_cittadini_illustri',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ComuneConfinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=500)),
                ('ordine', models.SmallIntegerField(default=0)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confinanti', to='comuni_italiani.comune')),
            ],
            options={
                'verbose_name': 'Comune confinante',
                'verbose_name_plural': 'Comuni confinanti',
                'db_table': 'comuni_italiani"."comune_confinanti',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ComuneEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('ordine', models.SmallIntegerField(default=0)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='comuni_italiani.comune')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'db_table': 'comuni_italiani"."comune_eventi',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ComuneFrazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('ordine', models.SmallIntegerField(default=0)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frazioni', to='comuni_italiani.comune')),
            ],
            options={
                'verbose_name': 'Frazione',
                'verbose_name_plural': 'Frazioni',
                'db_table': 'comuni_italiani"."comune_frazioni',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ComuneGemellaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citta', models.CharField(max_length=300)),
                ('ordine', models.SmallIntegerField(default=0)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gemellaggi', to='comuni_italiani.comune')),
            ],
            options={
                'verbose_name': 'Gemellaggio',
                'verbose_name_plural': 'Gemellaggi',
                'db_table': 'comuni_italiani"."comune_gemellaggi',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ComuniIstatRawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('regione', 'Regione'), ('provincia', 'Provincia'), ('comune', 'Comune')], max_length=20)),
                ('codice_istat', models.CharField(max_length=10)),
                ('regione', models.CharField(max_length=100)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('comune', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_json', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Raw Data',
                'verbose_name_plural': 'Raw Data',
                'db_table': 'comuni_italiani"."raw_data',
                'indexes': [models.Index(fields=['tipo'], name='raw_data_tipo_41f60a_idx'), models.Index(fields=['codice_istat'], name='raw_data_codice__0bc94e_idx'), models.Index(fields=['tipo', 'codice_istat'], name='raw_data_tipo_8f00a1_idx')],
            },
        ),
        migrations.AddField(
            model_name='comune',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuni', to='comuni_italiani.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='regione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province', to='comuni_italiani.regione'),
        ),
        migrations.CreateModel(
            name='ComunePuntoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('museo', 'Museo'), ('chiesa', 'Chiesa'), ('villa_palazzo', 'Villa / Palazzo'), ('castello_fortificazione', 'Castello / Fortificazione'), ('fontana', 'Fontana'), ('giardino_orto_botanico', 'Giardino / Orto Botanico'), ('luogo_interesse', 'Luogo di interesse'), ('teatro', 'Teatro'), ('stadio', 'Stadio')], max_length=50)),
                ('nome', models.CharField(max_length=500)),
                ('ordine', models.SmallIntegerField(default=0)),
                ('comune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punti_interesse', to='comuni_italiani.comune')),
            ],
            options={
                'verbose_name': 'Punto di interesse',
                'verbose_name_plural': 'Punti di interesse',
                'db_table': 'comuni_italiani"."comune_punti_interesse',
                'ordering': ['ordine'],
                'indexes': [models.Index(fields=['tipo'], name='ing_poi_tipo_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['nome'], name='ing_comuni_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['codice_istat'], name='ing_comuni_codice_idx'),
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['cap'], name='ing_comuni_cap_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['sigla'], name='ing_province_sigla_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['codice_istat'], name='ing_province_codice_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='provincia',
            unique_together={('regione', 'nome')},
        ),
    ]
