apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - tekton-ingressroute.yml
  - tekton-serviceaccount.yml
  - tekton-task-kaniko-build.yml
  - tekton-pipeline-build-and-push.yml
