# Generated by Django 5.0.1 on 2026-02-04 22:08

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComuneJsonStaging",
            fields=[
                (
                    "codice",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "codice_catastale",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "cap",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("popolazione", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Comune JSON Staging",
                "verbose_name_plural": "Comuni JSON Staging",
                "db_table": 'comuni_italiani"."comuni_json_staging',
            },
        ),
        migrations.CreateModel(
            name="RegioneItaliana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_reg", models.IntegerField(unique=True)),
                ("den_reg", models.CharField(max_length=50)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("shape_area", models.FloatField(blank=True, null=True)),
                ("shape_length", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Regione",
                "verbose_name_plural": "Regioni",
                "db_table": 'comuni_italiani"."regioni',
                "ordering": ["den_reg"],
            },
        ),
        migrations.CreateModel(
            name="RipartizioneGeografica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_rip", models.IntegerField(unique=True)),
                ("den_rip", models.CharField(max_length=50)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("shape_area", models.FloatField(blank=True, null=True)),
                ("shape_length", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Ripartizione Geografica",
                "verbose_name_plural": "Ripartizioni Geografiche",
                "db_table": 'comuni_italiani"."ripartizioni',
                "ordering": ["cod_rip"],
            },
        ),
        migrations.CreateModel(
            name="ProvinciaItaliana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_rip", models.IntegerField()),
                ("cod_prov", models.IntegerField()),
                ("cod_cm", models.IntegerField(blank=True, null=True)),
                ("cod_uts", models.IntegerField(unique=True)),
                ("den_prov", models.CharField(blank=True, max_length=50, null=True)),
                ("den_cm", models.CharField(blank=True, max_length=50, null=True)),
                ("den_uts", models.CharField(max_length=50)),
                ("sigla", models.CharField(max_length=2)),
                ("tipo_uts", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("shape_area", models.FloatField(blank=True, null=True)),
                ("shape_length", models.FloatField(blank=True, null=True)),
                (
                    "cod_reg",
                    models.ForeignKey(
                        db_column="cod_reg",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comuni_italiani.regioneitaliana",
                        to_field="cod_reg",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Province",
                "db_table": 'comuni_italiani"."province',
                "ordering": ["den_uts"],
            },
        ),
        migrations.AddField(
            model_name="regioneitaliana",
            name="cod_rip",
            field=models.ForeignKey(
                db_column="cod_rip",
                on_delete=django.db.models.deletion.CASCADE,
                to="comuni_italiani.ripartizionegeografica",
                to_field="cod_rip",
            ),
        ),
        migrations.CreateModel(
            name="ComuneItaliano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_rip", models.IntegerField()),
                ("cod_reg", models.IntegerField()),
                ("cod_prov", models.IntegerField()),
                ("cod_cm", models.IntegerField(blank=True, null=True)),
                ("pro_com", models.IntegerField(unique=True)),
                ("pro_com_t", models.CharField(max_length=6)),
                ("comune", models.CharField(max_length=100)),
                ("comune_a", models.CharField(blank=True, max_length=100, null=True)),
                ("cc_uts", models.IntegerField(blank=True, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("shape_area", models.FloatField(blank=True, null=True)),
                ("shape_length", models.FloatField(blank=True, null=True)),
                (
                    "codice_catastale",
                    models.CharField(blank=True, max_length=4, null=True),
                ),
                (
                    "cap",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("popolazione", models.IntegerField(blank=True, null=True)),
                (
                    "cod_uts",
                    models.ForeignKey(
                        db_column="cod_uts",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comuni_italiani.provinciaitaliana",
                        to_field="cod_uts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comune",
                "verbose_name_plural": "Comuni",
                "db_table": 'comuni_italiani"."comuni',
                "ordering": ["comune"],
                "indexes": [
                    models.Index(
                        fields=["pro_com_t"], name="comuni_pro_com_2c8845_idx"
                    ),
                    models.Index(fields=["comune"], name="comuni_comune_de3af3_idx"),
                    models.Index(fields=["cod_prov"], name="comuni_cod_pro_5f7b86_idx"),
                    models.Index(fields=["cod_reg"], name="comuni_cod_reg_548faf_idx"),
                    models.Index(
                        fields=["codice_catastale"], name="comuni_codice__008cbc_idx"
                    ),
                    models.Index(
                        fields=["popolazione"], name="comuni_popolaz_0f3025_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="provinciaitaliana",
            index=models.Index(fields=["sigla"], name="province_sigla_ea304b_idx"),
        ),
        migrations.AddIndex(
            model_name="provinciaitaliana",
            index=models.Index(fields=["cod_prov"], name="province_cod_pro_98589c_idx"),
        ),
    ]
