# Generated by Django 5.0.1 on 2026-03-22 12:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0000_create_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=32, unique=True)),
                ('content_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('source', models.CharField(db_comment='sorgente dati', db_index=True, max_length=50)),
                ('title', models.TextField()),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('status', models.CharField(choices=[('staging', 'Staging'), ('published', 'Pubblicato')], db_index=True, default='staging', max_length=20)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('location_coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('schema_org', models.JSONField(blank=True, db_comment='Schema.org/Event generato da AI', null=True)),
                ('batch_file', models.CharField(blank=True, db_comment='Nome file batch di provenienza', max_length=255, null=True)),
                ('rank_score', models.FloatField(db_index=True, default=0.0, help_text='Score calcolato automaticamente')),
                ('boost', models.SmallIntegerField(default=0, help_text='Override manuale redazione (-10..+10)')),
                ('created_by', models.CharField(blank=True, help_text="Username di chi ha creato l'evento", max_length=150, null=True)),
                ('updated_by', models.CharField(blank=True, help_text="Username di chi ha modificato l'evento", max_length=150, null=True)),
                ('deleted_by', models.CharField(blank=True, help_text="Username di chi ha disattivato l'evento (soft delete)", max_length=150, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'db_table': 'events_data"."events',
                'ordering': ['-created_at'],
            },
        ),
    ]
