# Generated by Django 5.0.1 on 2026-02-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_create_production_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productionevent",
            options={
                "ordering": ["-date_start", "-created_at"],
                "verbose_name": "Production Event",
                "verbose_name_plural": "Production Events",
            },
        ),
        migrations.AlterModelOptions(
            name="stagingevent",
            options={
                "ordering": ["-loaded_at"],
                "verbose_name": "Staging Event",
                "verbose_name_plural": "Staging Events",
            },
        ),
    ]
