# Generated by Django 5.0.1 on 2026-02-05 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_staging_missing_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionevent',
            options={'managed': False, 'ordering': ['-date_start', '-created_at'], 'verbose_name': 'Production Event', 'verbose_name_plural': 'Production Events'},
        ),
        migrations.AlterModelOptions(
            name='stagingevent',
            options={'managed': False, 'ordering': ['-loaded_at'], 'verbose_name': 'Staging Event', 'verbose_name_plural': 'Staging Events'},
        ),
    ]
