# Generated by Django 5.0.1 on 2026-02-20 22:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_stagingevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagingevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Staging Event', 'verbose_name_plural': 'Staging Events'},
        ),
        migrations.RenameField(
            model_name='stagingevent',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='stagingevent',
            old_name='loaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='stagingevent',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='stagingevent',
            name='website',
        ),
        migrations.RemoveField(
            model_name='stagingevent',
            name='weekdays',
        ),
        migrations.AddField(
            model_name='stagingevent',
            name='info_extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagingevent',
            name='location_coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='stagingevent',
            name='section',
            field=models.TextField(blank=True, db_comment='dati in base alla sezione', null=True),
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='source',
            field=models.CharField(db_comment='sorgente dati', max_length=50),
        ),
    ]
