# Generated by Django 5.0.1 on 2026-02-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_staging_pointfield_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingevent',
            name='section',
            field=models.JSONField(blank=True, db_comment='dati strutturati della sezione (cast, rassegna, ecc.)', null=True),
        ),
    ]
