# Generated by Django 5.0.1 on 2026-03-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_section_textfield_to_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagingevent',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='stagingevent',
            name='time_info',
        ),
        migrations.RemoveField(
            model_name='stagingevent',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='date_end',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='date_start',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
