# Generated by Django 5.0.1 on 2026-03-16 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_change_dates_to_char_remove_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingevent',
            name='schema_org',
            field=models.JSONField(blank=True, db_comment='Schema.org/Event generato da AI', null=True),
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
