# Generated by Django 5.0.1 on 2026-03-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_dates_to_datetime_add_schema_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingevent',
            name='batch_file',
            field=models.CharField(blank=True, db_comment='Nome file batch di provenienza', max_length=255, null=True),
        ),
    ]
