# Generated by Django 5.0.1 on 2026-03-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_remove_stagingevent_info_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagingevent',
            name='city_name',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='content_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='source',
            field=models.CharField(db_comment='sorgente dati', db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stagingevent',
            name='uuid',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
