# Generated by Django 5.0.1 on 2026-03-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaCitta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('ordine', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagina Città',
                'verbose_name_plural': 'Pagine Città',
                'ordering': ['ordine', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SezioneEventi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('colore', models.CharField(choices=[('blue', 'Blu'), ('green', 'Verde'), ('red', 'Rosso'), ('orange', 'Arancione'), ('yellow', 'Giallo'), ('purple', 'Viola')], default='blue', max_length=20)),
                ('link_vedi_tutti', models.CharField(blank=True, max_length=200, verbose_name='Link "Vedi tutti"')),
                ('ordine', models.IntegerField(default=0)),
                ('is_attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sezioni_eventi', to='cms.paginacitta')),
            ],
            options={
                'verbose_name': 'Sezione Eventi',
                'verbose_name_plural': 'Sezioni Eventi',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='EventoSelezionato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Evento')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='cms.sezioneeventi')),
            ],
            options={
                'verbose_name': 'Evento Selezionato',
                'verbose_name_plural': 'Eventi Selezionati',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='SezionePagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('colore', models.CharField(choices=[('blue', 'Blu'), ('green', 'Verde'), ('red', 'Rosso'), ('orange', 'Arancione'), ('yellow', 'Giallo'), ('purple', 'Viola')], default='blue', max_length=20)),
                ('link_vedi_tutti', models.CharField(blank=True, max_length=200, verbose_name='Link "Vedi tutti"')),
                ('ordine', models.IntegerField(default=0)),
                ('is_attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sezioni', to='cms.paginacitta')),
            ],
            options={
                'verbose_name': 'Sezione Pagina',
                'verbose_name_plural': 'Sezioni Pagina',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='EventoInSezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Evento')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='cms.sezionepagina')),
            ],
            options={
                'verbose_name': 'Evento (da Staging)',
                'verbose_name_plural': 'Eventi (da Staging)',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='ArticoloSezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='cms/articoli/')),
                ('immagine_url', models.URLField(blank=True, verbose_name='Immagine URL (alternativa)')),
                ('categoria', models.CharField(blank=True, max_length=50, verbose_name='Occhiello')),
                ('colore_categoria', models.CharField(choices=[('red', 'Rosso'), ('blue', 'Blu'), ('green', 'Verde'), ('orange', 'Arancione')], default='red', max_length=10, verbose_name='Colore occhiello')),
                ('url', models.CharField(max_length=200)),
                ('ordine', models.IntegerField(default=0)),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='cms.sezionepagina')),
            ],
            options={
                'verbose_name': 'Articolo',
                'verbose_name_plural': 'Articoli',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='TabNavigazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('ordine', models.IntegerField(default=0)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigazione', to='cms.paginacitta')),
            ],
            options={
                'verbose_name': 'Tab Navigazione',
                'verbose_name_plural': 'Tab Navigazione',
                'ordering': ['ordine'],
            },
        ),
    ]
