# Generated by Django 5.0.1 on 2026-02-13 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('events', '0007_alter_stagingevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SezioneEventi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('colore', models.CharField(choices=[('blue', 'Blu'), ('green', 'Verde'), ('red', 'Rosso'), ('orange', 'Arancione'), ('yellow', 'Giallo'), ('purple', 'Viola')], default='blue', max_length=20)),
                ('link_vedi_tutti', models.CharField(blank=True, max_length=200, verbose_name='Link "Vedi tutti"')),
                ('ordine', models.IntegerField(default=0)),
                ('is_attiva', models.BooleanField(default=True, verbose_name='Attiva')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sezioni_eventi', to='cms.paginacitta')),
            ],
            options={
                'verbose_name': 'Sezione Eventi',
                'verbose_name_plural': 'Sezioni Eventi',
                'ordering': ['ordine'],
            },
        ),
        migrations.CreateModel(
            name='EventoSelezionato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.stagingevent', verbose_name='Staging Event')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='cms.sezioneeventi')),
            ],
            options={
                'verbose_name': 'Evento Selezionato',
                'verbose_name_plural': 'Eventi Selezionati',
                'ordering': ['ordine'],
            },
        ),
    ]
