# Generated by Django 5.0.1 on 2026-02-13 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_sezioneeventi_eventoselezionato'),
        ('events', '0007_alter_stagingevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoInSezione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(default=0)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.stagingevent', verbose_name='Staging Event')),
                ('sezione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to='cms.sezionepagina')),
            ],
            options={
                'verbose_name': 'Evento (da Staging)',
                'verbose_name_plural': 'Eventi (da Staging)',
                'ordering': ['ordine'],
            },
        ),
    ]
