# Generated by Django 5.0.1 on 2026-03-22 12:09

import api_consumers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Identificativo univoco del consumer', max_length=100, unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('enterprise', 'Enterprise'), ('flat', 'Flat')], default='free', max_length=20)),
                ('auth_type', models.CharField(choices=[('api_key', 'API Key (APISIX)'), ('jwt', 'JWT (Keycloak)')], default='api_key', help_text="API Key: autenticazione via APISIX. JWT: client Keycloak con claim 'plan'.", max_length=10)),
                ('api_key', models.CharField(blank=True, help_text='Generata automaticamente alla creazione', max_length=255, null=True, unique=True)),
                ('keycloak_client_id', models.CharField(blank=True, max_length=255)),
                ('keycloak_client_secret', models.CharField(blank=True, max_length=255)),
                ('api_permissions', models.JSONField(default=api_consumers.models.default_api_permissions, help_text='Permessi per risorsa e azione. Formato: {risorsa: [azioni]}', verbose_name='Permessi API')),
                ('contact_email', models.EmailField(blank=True, help_text='Email di contatto', max_length=254)),
                ('description', models.TextField(blank=True, help_text='Note interne')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data di scadenza. Lasciare vuoto per accesso illimitato.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('apisix_synced', models.BooleanField(default=False, editable=False)),
                ('keycloak_synced', models.BooleanField(default=False, editable=False)),
                ('sync_error', models.TextField(blank=True, editable=False)),
                ('last_synced_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('django_user', models.ForeignKey(blank=True, help_text='Utente Django proprietario di questo consumer (opzionale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_consumers', to=settings.AUTH_USER_MODEL, verbose_name='Utente Django')),
            ],
            options={
                'verbose_name': 'API Consumer',
                'verbose_name_plural': 'API Consumers',
                'db_table': 'api_consumers',
                'ordering': ['-created_at'],
            },
        ),
    ]
