# Generated by Django 5.0.1 on 2026-03-21 11:47

import api_consumers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_consumers', '0003_apiconsumer_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconsumer',
            name='api_permissions',
            field=models.JSONField(default=api_consumers.models.default_api_permissions, help_text='Permessi per risorsa e azione. Formato: {risorsa: [azioni]}', verbose_name='Permessi API'),
        ),
    ]
