# Generated by Django 5.0.1 on 2026-03-21 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_consumers', '0004_add_api_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconsumer',
            name='django_user',
            field=models.ForeignKey(blank=True, help_text='Utente Django proprietario di questo consumer (opzionale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_consumers', to=settings.AUTH_USER_MODEL, verbose_name='Utente Django'),
        ),
    ]
