# APISIX Helm values
apisix:
  image:
    repository: apache/apisix
    tag: "3.11-debian"
  kind: Deployment
  replicaCount: 1
  nodeSelector:
    workload: heavy
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

gateway:
  type: ClusterIP
  http:
    enabled: true
    servicePort: 9080
    containerPort: 9080

admin:
  enabled: true
  type: ClusterIP
  port: 9180
  credentials:
    admin: apisix-admin-key
    viewer: apisix-viewer-key

etcd:
  enabled: true
  replicaCount: 1
  persistence:
    size: 2Gi
  nodeSelector:
    workload: light

dashboard:
  enabled: true
  image:
    repository: apache/apisix-dashboard
    tag: "3.0-alpine"

ingress-controller:
  enabled: true
  config:
    apisix:
      serviceNamespace: apps
      adminKey: apisix-admin-key

pluginAttrs:
  prometheus:
    export_addr:
      ip: 0.0.0.0
      port: 9091
  opentelemetry:
    resource:
      service.name: apisix-gateway
    collector:
      address: otel-collector.monitoring.svc:4317
      request_timeout: 3
