apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
  namespace: events
  labels:
    app: postgres
data:
  01-extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS postgis;
    CREATE EXTENSION IF NOT EXISTS postgis_topology;
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
