# Generated by Django 5.0.1 on 2026-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtlError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('json_file', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ETL Error',
                'verbose_name_plural': 'ETL Errors',
                'db_table': 'etl_errors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EtlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(max_length=50)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='running', max_length=20)),
                ('staging_count', models.IntegerField(default=0)),
                ('inserted_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('staging_completed_at', models.DateTimeField(blank=True, null=True)),
                ('upsert_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ETL Run',
                'verbose_name_plural': 'ETL Runs',
                'db_table': 'etl_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, help_text='W3C Trace ID (32 hex chars)', max_length=32)),
                ('span_id', models.CharField(blank=True, help_text='Span ID corrente', max_length=16, null=True)),
                ('parent_span_id', models.CharField(blank=True, max_length=16, null=True)),
                ('service', models.CharField(help_text='Nome del servizio (es. backoffice-django, scraping-service)', max_length=50)),
                ('operation', models.CharField(help_text='Operazione (es. bulk.received, event.validated)', max_length=100)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Dettaglio o messaggio errore', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Dati strutturati (spider, uuid eventi, conteggi)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trace Log',
                'verbose_name_plural': 'Trace Logs',
                'db_table': 'trace_logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trace_id', 'created_at'], name='trace_logs_trace_i_45007c_idx'), models.Index(fields=['level'], name='trace_logs_level_fa76ba_idx'), models.Index(fields=['-created_at'], name='trace_logs_created_8a30fc_idx')],
            },
        ),
    ]
