# Generated by Django 5.0.1 on 2026-03-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_create_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, help_text='W3C Trace ID (32 hex chars)', max_length=32)),
                ('span_id', models.CharField(blank=True, help_text='Span ID corrente', max_length=16, null=True)),
                ('parent_span_id', models.CharField(blank=True, max_length=16, null=True)),
                ('service', models.CharField(help_text='Nome del servizio (es. backoffice-django, scraping-service)', max_length=50)),
                ('operation', models.CharField(help_text='Operazione (es. bulk.received, event.validated)', max_length=100)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Dettaglio o messaggio errore', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Dati strutturati (spider, uuid eventi, conteggi)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trace Log',
                'verbose_name_plural': 'Trace Logs',
                'db_table': 'trace_logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trace_id', 'created_at'], name='trace_logs_trace_i_45007c_idx'), models.Index(fields=['level'], name='trace_logs_level_fa76ba_idx'), models.Index(fields=['-created_at'], name='trace_logs_created_8a30fc_idx')],
            },
        ),
    ]
