# IngressRoute per Kong Manager — Admin UI integrata in Kong
# Protetto da google-auth middleware (OAuth2 Proxy)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: kong-manager-https
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`kong.oci.santocaruso.eu`)
      kind: Rule
      services:
        - name: kong-kong-manager
          port: 8002
      middlewares:
        - name: google-auth
          namespace: traefik
  tls:
    certResolver: letsencrypt
