apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kong-ingressroute.yml
  - kong-gateway-ingressroute.yml
  - kong-manager-ingressroute.yml
  - kong-admin-ingressroute.yml
