apiVersion: v1
kind: ConfigMap
metadata:
  name: backoffice-config
  namespace: apps
  labels:
    app: backoffice
    component: web
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "events.oci.santocaruso.eu,localhost,backoffice.apps.svc"
  POSTGRES_HOST: "postgres.database.svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "events"
  POSTGRES_USER: "events"
  CORS_ALLOWED_ORIGINS: "https://events.oci.santocaruso.eu"
  CSRF_TRUSTED_ORIGINS: "https://events.oci.santocaruso.eu"
  OTEL_ENABLED: "false"
  OTEL_SERVICE_NAME: "backoffice-django"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.monitoring.svc:4317"
