# Generated by Django 5.0.1 on 2026-02-04 22:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=16, unique=True)),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("source", models.CharField(max_length=50)),
                ("url", models.TextField(blank=True, null=True)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("image_url", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location_address", models.TextField(blank=True, null=True)),
                ("price", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("time_info", models.TextField(blank=True, null=True)),
                ("schedule", models.TextField(blank=True, null=True)),
                ("weekdays", models.TextField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Production Event",
                "verbose_name_plural": "Production Events",
                "db_table": 'events_data"."production_events',
                "ordering": ["-date_start", "-created_at"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StagingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.CharField(max_length=16)),
                (
                    "content_hash",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("source", models.CharField(max_length=50)),
                ("url", models.TextField(blank=True, null=True)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, null=True, size=None
                    ),
                ),
                ("image_url", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location_address", models.TextField(blank=True, null=True)),
                ("price", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                ("time_start", models.TimeField(blank=True, null=True)),
                ("time_end", models.TimeField(blank=True, null=True)),
                ("time_info", models.TextField(blank=True, null=True)),
                ("schedule", models.TextField(blank=True, null=True)),
                ("weekdays", models.TextField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(blank=True, null=True)),
                ("loaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Staging Event",
                "verbose_name_plural": "Staging Events",
                "db_table": 'events_data"."staging_events',
                "ordering": ["-loaded_at"],
                "managed": False,
            },
        ),
    ]
