# Generated by Django 5.0.1 on 2026-02-06 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_productionevent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagingevent',
            options={'ordering': ['-loaded_at'], 'verbose_name': 'Staging Event', 'verbose_name_plural': 'Staging Events'},
        ),
    ]
