apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: daily-full-backup
  namespace: velero
spec:
  schedule: "0 2 * * *"
  template:
    ttl: "168h"
    includedNamespaces:
      - events
      - monitoring
    storageLocation: oci-objectstorage
    defaultVolumesToFsBackup: true
