apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-ui
  labels:
    app: velero-ui
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["velero.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-ui
  labels:
    app: velero-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: velero-ui
subjects:
  - kind: ServiceAccount
    name: velero-ui
    namespace: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-ui
  namespace: velero
  labels:
    app: velero-ui
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["velero.io"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-ui
  namespace: velero
  labels:
    app: velero-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: velero-ui
subjects:
  - kind: ServiceAccount
    name: velero-ui
    namespace: velero
