# Generated by Django 5.0.1 on 2026-03-22 12:09

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comuni_italiani', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComuneJsonStaging',
            fields=[
                ('codice', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('codice_catastale', models.CharField(blank=True, max_length=4, null=True)),
                ('cap', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('popolazione', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Comune JSON Staging',
                'verbose_name_plural': 'Comuni JSON Staging',
                'db_table': 'comuni_istat"."comuni_json_staging',
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_reg', models.IntegerField(unique=True)),
                ('den_reg', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'db_table': 'comuni_istat"."regioni',
                'ordering': ['den_reg'],
            },
        ),
        migrations.CreateModel(
            name='RipartizioneGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_rip', models.IntegerField(unique=True)),
                ('den_rip', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ripartizione Geografica',
                'verbose_name_plural': 'Ripartizioni Geografiche',
                'db_table': 'comuni_istat"."ripartizioni',
                'ordering': ['cod_rip'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_rip', models.IntegerField()),
                ('cod_prov', models.IntegerField()),
                ('cod_cm', models.IntegerField(blank=True, null=True)),
                ('cod_uts', models.IntegerField(unique=True)),
                ('den_prov', models.CharField(blank=True, max_length=50, null=True)),
                ('den_cm', models.CharField(blank=True, max_length=50, null=True)),
                ('den_uts', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
                ('tipo_uts', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('provincia_ingestion', models.OneToOneField(blank=True, db_column='provincia_ingestion_id', help_text='Collegamento alla provincia in comuni_italiani (match per sigla)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provincia_istat', to='comuni_italiani.provincia')),
                ('cod_reg', models.ForeignKey(db_column='cod_reg', on_delete=django.db.models.deletion.CASCADE, to='comuni_istat.regione', to_field='cod_reg')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'db_table': 'comuni_istat"."province',
                'ordering': ['den_uts'],
            },
        ),
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_rip', models.IntegerField()),
                ('cod_reg', models.IntegerField()),
                ('cod_prov', models.IntegerField()),
                ('cod_cm', models.IntegerField(blank=True, null=True)),
                ('pro_com', models.IntegerField(unique=True)),
                ('pro_com_t', models.CharField(max_length=6)),
                ('comune', models.CharField(max_length=100)),
                ('comune_a', models.CharField(blank=True, max_length=100, null=True)),
                ('cc_uts', models.IntegerField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('shape_area', models.FloatField(blank=True, null=True)),
                ('shape_length', models.FloatField(blank=True, null=True)),
                ('attivo', models.BooleanField(default=True, help_text='False se soppresso/fuso in altro comune')),
                ('codice_catastale', models.CharField(blank=True, max_length=4, null=True)),
                ('cap', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, null=True, size=None)),
                ('popolazione', models.IntegerField(blank=True, null=True)),
                ('altitudine', models.SmallIntegerField(blank=True, help_text='Altitudine del centro (m)', null=True)),
                ('zona_altimetrica', models.SmallIntegerField(blank=True, help_text='1=Montagna int., 2=Montagna lit., 3=Collina int., 4=Collina lit., 5=Pianura', null=True)),
                ('comune_litoraneo', models.BooleanField(blank=True, null=True)),
                ('comune_isolano', models.BooleanField(blank=True, null=True)),
                ('zona_costiera', models.SmallIntegerField(blank=True, help_text='Zona costiera ISTAT 2021', null=True)),
                ('grado_urbanizzazione', models.SmallIntegerField(blank=True, help_text='DEGURBA 2021: 1=Densamente, 2=Mediamente, 3=Scarsamente', null=True)),
                ('ecoregione_divisione', models.CharField(blank=True, max_length=100, null=True)),
                ('ecoregione_provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('ecoregione_sezione', models.CharField(blank=True, max_length=100, null=True)),
                ('ecoregione_sottosezione', models.CharField(blank=True, max_length=200, null=True)),
                ('comune_ingestion', models.OneToOneField(blank=True, db_column='comune_ingestion_id', help_text='Collegamento al comune in comuni_italiani (match per codice catastale)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comune_istat', to='comuni_italiani.comune')),
                ('cod_uts', models.ForeignKey(db_column='cod_uts', on_delete=django.db.models.deletion.CASCADE, to='comuni_istat.provincia', to_field='cod_uts')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'db_table': 'comuni_istat"."comuni',
                'ordering': ['comune'],
            },
        ),
        migrations.AddField(
            model_name='regione',
            name='cod_rip',
            field=models.ForeignKey(db_column='cod_rip', on_delete=django.db.models.deletion.CASCADE, to='comuni_istat.ripartizionegeografica', to_field='cod_rip'),
        ),
        migrations.CreateModel(
            name='ComuneSoppresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.SmallIntegerField()),
                ('pro_com_t', models.CharField(help_text='Codice ISTAT del comune soppresso', max_length=6)),
                ('comune', models.CharField(help_text='Nome del comune soppresso', max_length=100)),
                ('sigla_uts', models.CharField(max_length=2)),
                ('cod_variazione', models.CharField(choices=[('ES', 'Estinzione'), ('AS', 'Acquisizione/Scorporo')], max_length=2)),
                ('data_inizio', models.CharField(blank=True, max_length=20, null=True)),
                ('pro_com_t_rel', models.CharField(help_text='Codice ISTAT del comune associato (attuale)', max_length=6)),
                ('comune_rel', models.CharField(help_text='Nome del comune associato (attuale)', max_length=100)),
                ('sigla_uts_rel', models.CharField(blank=True, max_length=2, null=True)),
                ('comune_attuale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuni_soppressi', to='comuni_istat.comune')),
            ],
            options={
                'verbose_name': 'Comune soppresso',
                'verbose_name_plural': 'Comuni soppressi',
                'db_table': 'comuni_istat"."comuni_soppressi',
                'ordering': ['-anno', 'comune'],
                'indexes': [models.Index(fields=['pro_com_t'], name='comuni_sopp_pro_com_03379f_idx'), models.Index(fields=['pro_com_t_rel'], name='comuni_sopp_pro_com_e162ef_idx'), models.Index(fields=['comune'], name='comuni_sopp_comune_0af1de_idx')],
            },
        ),
        migrations.CreateModel(
            name='DenominazionePrecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_com_t', models.CharField(max_length=6)),
                ('comune', models.CharField(help_text='Denominazione precedente', max_length=100)),
                ('sigla_uts', models.CharField(max_length=20)),
                ('cod_den_storico', models.CharField(max_length=10)),
                ('pro_com_t_corrente', models.CharField(max_length=6)),
                ('comune_corrente', models.CharField(help_text='Denominazione corrente', max_length=100)),
                ('sigla_uts_corrente', models.CharField(blank=True, max_length=10, null=True)),
                ('comune_attuale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denominazioni_precedenti', to='comuni_istat.comune')),
            ],
            options={
                'verbose_name': 'Denominazione precedente',
                'verbose_name_plural': 'Denominazioni precedenti',
                'db_table': 'comuni_istat"."denominazioni_precedenti',
                'ordering': ['comune'],
                'indexes': [models.Index(fields=['pro_com_t_corrente'], name='denominazio_pro_com_0d0f70_idx'), models.Index(fields=['comune'], name='denominazio_comune_790574_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['pro_com_t'], name='comuni_pro_com_2c8845_idx'),
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['comune'], name='comuni_comune_de3af3_idx'),
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['cod_prov'], name='comuni_cod_pro_5f7b86_idx'),
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['cod_reg'], name='comuni_cod_reg_548faf_idx'),
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['codice_catastale'], name='comuni_codice__008cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='comune',
            index=models.Index(fields=['popolazione'], name='comuni_popolaz_0f3025_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['sigla'], name='province_sigla_ea304b_idx'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['cod_prov'], name='province_cod_pro_98589c_idx'),
        ),
    ]
