# Generated by Django 5.0.1 on 2026-03-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_istat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComuneSoppresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno', models.SmallIntegerField()),
                ('pro_com_t', models.CharField(help_text='Codice ISTAT del comune soppresso', max_length=6)),
                ('comune', models.CharField(help_text='Nome del comune soppresso', max_length=100)),
                ('sigla_uts', models.CharField(max_length=2)),
                ('cod_variazione', models.CharField(choices=[('ES', 'Estinzione'), ('AS', 'Acquisizione/Scorporo')], max_length=2)),
                ('data_inizio', models.CharField(blank=True, max_length=20, null=True)),
                ('pro_com_t_rel', models.CharField(help_text='Codice ISTAT del comune associato (attuale)', max_length=6)),
                ('comune_rel', models.CharField(help_text='Nome del comune associato (attuale)', max_length=100)),
                ('sigla_uts_rel', models.CharField(blank=True, max_length=2, null=True)),
                ('comune_attuale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comuni_soppressi', to='comuni_istat.comuneitaliano')),
            ],
            options={
                'verbose_name': 'Comune soppresso',
                'verbose_name_plural': 'Comuni soppressi',
                'db_table': 'comuni_istat"."comuni_soppressi',
                'ordering': ['-anno', 'comune'],
                'indexes': [models.Index(fields=['pro_com_t'], name='comuni_sopp_pro_com_03379f_idx'), models.Index(fields=['pro_com_t_rel'], name='comuni_sopp_pro_com_e162ef_idx'), models.Index(fields=['comune'], name='comuni_sopp_comune_0af1de_idx')],
            },
        ),
    ]
