# Generated by Django 5.0.1 on 2026-03-08 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_istat', '0002_comuni_soppressi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominazionePrecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_com_t', models.CharField(max_length=6)),
                ('comune', models.CharField(help_text='Denominazione precedente', max_length=100)),
                ('sigla_uts', models.CharField(max_length=2)),
                ('cod_den_storico', models.CharField(max_length=10)),
                ('pro_com_t_corrente', models.CharField(max_length=6)),
                ('comune_corrente', models.CharField(help_text='Denominazione corrente', max_length=100)),
                ('sigla_uts_corrente', models.CharField(blank=True, max_length=2, null=True)),
                ('comune_attuale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='denominazioni_precedenti', to='comuni_istat.comuneitaliano')),
            ],
            options={
                'verbose_name': 'Denominazione precedente',
                'verbose_name_plural': 'Denominazioni precedenti',
                'db_table': 'comuni_istat"."denominazioni_precedenti',
                'ordering': ['comune'],
                'indexes': [models.Index(fields=['pro_com_t_corrente'], name='denominazio_pro_com_0d0f70_idx'), models.Index(fields=['comune'], name='denominazio_comune_790574_idx')],
            },
        ),
    ]
