# Generated by Django 5.0.1 on 2026-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_istat', '0003_denominazioni_precedenti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominazioneprecedente',
            name='sigla_uts_corrente',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
