# Generated by Django 5.0.1 on 2026-03-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_istat', '0004_fix_sigla_uts_corrente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denominazioneprecedente',
            name='sigla_uts',
            field=models.CharField(max_length=20),
        ),
    ]
