# Generated by Django 5.0.1 on 2026-03-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_istat', '0005_fix_sigla_uts_denominazioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuneitaliano',
            name='altitudine',
            field=models.SmallIntegerField(blank=True, help_text='Altitudine del centro (m)', null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='comune_isolano',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='comune_litoraneo',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='ecoregione_divisione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='ecoregione_provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='ecoregione_sezione',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='ecoregione_sottosezione',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='grado_urbanizzazione',
            field=models.SmallIntegerField(blank=True, help_text='DEGURBA 2021: 1=Densamente, 2=Mediamente, 3=Scarsamente', null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='zona_altimetrica',
            field=models.SmallIntegerField(blank=True, help_text='1=Montagna int., 2=Montagna lit., 3=Collina int., 4=Collina lit., 5=Pianura', null=True),
        ),
        migrations.AddField(
            model_name='comuneitaliano',
            name='zona_costiera',
            field=models.SmallIntegerField(blank=True, help_text='Zona costiera ISTAT 2021', null=True),
        ),
    ]
