# Generated by Django 5.0.1 on 2026-03-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comuni_istat', '0006_caratteristiche_comuni'),
    ]

    operations = [
        migrations.AddField(
            model_name='comuneitaliano',
            name='attivo',
            field=models.BooleanField(default=True, help_text='False se soppresso/fuso in altro comune'),
        ),
    ]
