#!/bin/bash

# Script to configure Oracle Container Registry (OCIR) with Portainer and Docker Swarm
# Author: Generated by Claude Code
# Date: 2026-01-10

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ANSIBLE_DIR="${PROJECT_ROOT}/ansible"
VARS_FILE="${ANSIBLE_DIR}/vars/ocir.yml"
VARS_EXAMPLE="${ANSIBLE_DIR}/vars/ocir.yml.example"

echo "==========================================="
echo "  OCIR Configuration for Portainer"
echo "==========================================="
echo ""

# Check if ansible directory exists
if [ ! -d "${ANSIBLE_DIR}" ]; then
    echo "❌ Error: ansible directory not found at ${ANSIBLE_DIR}"
    exit 1
fi

# Check if vars directory exists, create if not
if [ ! -d "${ANSIBLE_DIR}/vars" ]; then
    echo "📁 Creating vars directory..."
    mkdir -p "${ANSIBLE_DIR}/vars"
fi

# Check if ocir.yml exists
if [ ! -f "${VARS_FILE}" ]; then
    echo "⚠️  OCIR configuration file not found!"
    echo ""
    echo "You have two options to configure OCIR:"
    echo ""
    echo "1. AUTO-CONFIGURE using OCI CLI (recommended)"
    echo "   ./get-ocir-config.sh"
    echo ""
    echo "2. MANUAL configuration by editing the file"
    echo "   Copy and edit the example file"
    echo ""
    read -p "Do you want to use AUTO-CONFIGURE with OCI CLI? (yes/no): " -r
    echo ""

    if [[ $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
        # Run the auto-config script
        GET_CONFIG_SCRIPT="${SCRIPT_DIR}/get-ocir-config.sh"
        if [ -f "${GET_CONFIG_SCRIPT}" ]; then
            "${GET_CONFIG_SCRIPT}"
            echo ""
            echo "Configuration completed. Continuing with OCIR setup..."
            echo ""
        else
            echo "❌ Error: get-ocir-config.sh not found at ${GET_CONFIG_SCRIPT}"
            exit 1
        fi
    else
        # Manual configuration
        if [ -f "${VARS_EXAMPLE}" ]; then
            echo "📋 Copying example configuration..."
            cp "${VARS_EXAMPLE}" "${VARS_FILE}"
            echo ""
            echo "✅ Created ${VARS_FILE}"
            echo ""
            echo "📝 Please edit the file and configure your OCIR credentials:"
            echo "   ${VARS_FILE}"
            echo ""
            echo "Required information:"
            echo "  1. OCI Region (e.g., eu-milan-1)"
            echo "  2. Tenancy Namespace (find in OCI Console -> Tenancy -> Object Storage Namespace)"
            echo "  3. OCI Username (your OCI login email)"
            echo "  4. Auth Token (generate in OCI Console -> User Settings -> Auth Tokens)"
            echo "  5. Portainer admin password"
            echo ""
            echo "TIP: You can also get this info via CLI:"
            echo "  ./get-ocir-config.sh"
            echo ""

            # Ask if user wants to edit now
            read -p "Do you want to edit the configuration file now? (yes/no): " -r
            echo ""

            if [[ $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
                # Try to find a text editor
                if command -v nano &> /dev/null; then
                    nano "${VARS_FILE}"
                elif command -v vim &> /dev/null; then
                    vim "${VARS_FILE}"
                elif command -v vi &> /dev/null; then
                    vi "${VARS_FILE}"
                else
                    echo "No text editor found. Please edit manually: ${VARS_FILE}"
                    exit 1
                fi
            else
                echo "Please edit the file and run this script again."
                exit 0
            fi
        else
            echo "❌ Error: Example file not found at ${VARS_EXAMPLE}"
            exit 1
        fi
    fi
fi

# Verify required fields are not default values
echo "🔍 Checking configuration..."

if grep -q "your-tenancy-namespace" "${VARS_FILE}" || \
   grep -q "your-oci-username@example.com" "${VARS_FILE}" || \
   grep -q "your-auth-token-here" "${VARS_FILE}" || \
   grep -q "your-portainer-admin-password" "${VARS_FILE}"; then
    echo ""
    echo "⚠️  WARNING: Configuration file contains default values!"
    echo ""
    echo "Please update the following in ${VARS_FILE}:"
    echo "  - ocir_tenancy_namespace"
    echo "  - ocir_username"
    echo "  - ocir_auth_token"
    echo "  - portainer_admin_password"
    echo ""
    read -p "Do you want to continue anyway? (yes/no): " -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
        exit 0
    fi
fi

# Check if Ansible is installed
if ! command -v ansible-playbook &> /dev/null; then
    echo "❌ Error: ansible-playbook not found. Please install Ansible first."
    exit 1
fi

# Run the playbook
echo "🚀 Configuring OCIR with Portainer..."
echo ""

cd "${ANSIBLE_DIR}"

if ansible-playbook playbooks/configure-ocir.yml; then
    echo ""
    echo "=========================================="
    echo "✅ OCIR Configuration Completed!"
    echo "=========================================="
    echo ""
else
    echo ""
    echo "❌ Configuration failed. Please check the errors above."
    exit 1
fi
