#!/bin/bash

# Script to generate SSH key pair for OCI instances
# Author: Generated by Claude Code
# Date: 2026-01-10

set -e

KEY_NAME="oci-key"
KEY_PATH="$(dirname "$0")/${KEY_NAME}"

echo "==========================================="
echo "  OCI SSH Key Generator"
echo "==========================================="
echo ""

# Check if keys already exist
if [ -f "${KEY_PATH}" ] || [ -f "${KEY_PATH}.pub" ]; then
    echo "⚠️  SSH keys already exist:"
    [ -f "${KEY_PATH}" ] && echo "   - ${KEY_PATH}"
    [ -f "${KEY_PATH}.pub" ] && echo "   - ${KEY_PATH}.pub"
    echo ""
    read -p "Do you want to overwrite them? (yes/no): " -r
    echo ""

    if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
        echo "❌ Operation cancelled."
        exit 0
    fi

    echo "🗑️  Removing existing keys..."
    rm -f "${KEY_PATH}" "${KEY_PATH}.pub"
fi

# Generate new SSH key pair
echo "🔑 Generating new SSH key pair..."
ssh-keygen -t rsa -b 4096 -f "${KEY_PATH}" -N "" -C "oci-2m-key"

# Set correct permissions
chmod 600 "${KEY_PATH}"
chmod 644 "${KEY_PATH}.pub"

echo ""
echo "✅ SSH key pair generated successfully!"
echo ""
echo "Private key: ${KEY_PATH}"
echo "Public key:  ${KEY_PATH}.pub"
echo ""
echo "🔒 Permissions set correctly (600 for private, 644 for public)"
echo ""
echo "📝 Next steps:"
echo "   1. The public key has been automatically configured in terraform.tfvars"
echo "   2. Run 'terraform apply' to update your OCI instances"
echo "   3. The private key is already configured in ansible/inventory.yml"
echo ""
echo "⚠️  IMPORTANT: Never commit the private key (${KEY_NAME}) to Git!"
echo "   (It's already in .gitignore)"
echo ""
