#!/bin/bash

# Script to automatically retrieve OCIR configuration from OCI CLI
# Author: Generated by Claude Code
# Date: 2026-01-10

set -e

echo "==========================================="
echo "  OCIR Auto-Configuration Helper"
echo "==========================================="
echo ""

# Check if OCI CLI is installed
if ! command -v oci &> /dev/null; then
    echo "❌ Error: OCI CLI not found."
    echo ""
    echo "Install OCI CLI:"
    echo "  macOS: brew install oci-cli"
    echo "  Linux: bash -c \"\$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)\""
    echo ""
    echo "Then configure it:"
    echo "  oci setup config"
    echo ""
    exit 1
fi

# Check if OCI CLI is configured
if [ ! -f ~/.oci/config ]; then
    echo "❌ Error: OCI CLI not configured."
    echo ""
    echo "Run: oci setup config"
    echo ""
    exit 1
fi

echo "✅ OCI CLI found and configured"
echo ""

# Get profile to use (default or specified)
OCI_PROFILE="${OCI_PROFILE:-DEFAULT}"
echo "Using OCI profile: ${OCI_PROFILE}"
echo ""

# Extract configuration from OCI config file
echo "📋 Retrieving configuration from OCI CLI..."
echo ""

# Get tenancy OCID
TENANCY_OCID=$(grep -A 10 "^\[${OCI_PROFILE}\]" ~/.oci/config | grep "^tenancy" | cut -d'=' -f2 | tr -d ' ')

# Get user OCID
USER_OCID=$(grep -A 10 "^\[${OCI_PROFILE}\]" ~/.oci/config | grep "^user" | cut -d'=' -f2 | tr -d ' ')

# Get region
REGION=$(grep -A 10 "^\[${OCI_PROFILE}\]" ~/.oci/config | grep "^region" | cut -d'=' -f2 | tr -d ' ')

# Get Object Storage Namespace
echo "🔍 Fetching Object Storage Namespace..."
NAMESPACE=$(oci os ns get --profile "${OCI_PROFILE}" 2>/dev/null | jq -r '.data')

if [ -z "$NAMESPACE" ] || [ "$NAMESPACE" == "null" ]; then
    echo "⚠️  Could not retrieve namespace automatically"
    echo ""
    read -p "Enter your Object Storage Namespace manually: " NAMESPACE
fi

# Get user details
echo "🔍 Fetching user details..."
USER_NAME=$(oci iam user get --user-id "${USER_OCID}" --profile "${OCI_PROFILE}" 2>/dev/null | jq -r '.data.name')

if [ -z "$USER_NAME" ] || [ "$USER_NAME" == "null" ]; then
    echo "⚠️  Could not retrieve username automatically"
    echo ""
    read -p "Enter your OCI username (email): " USER_NAME
fi

# Display collected information
echo ""
echo "=========================================="
echo "  Retrieved Configuration:"
echo "=========================================="
echo "Region:             ${REGION}"
echo "Namespace:          ${NAMESPACE}"
echo "Username:           ${USER_NAME}"
echo "Tenancy OCID:       ${TENANCY_OCID}"
echo "User OCID:          ${USER_OCID}"
echo ""

# Ask about Auth Token
echo "=========================================="
echo "  Auth Token Configuration"
echo "=========================================="
echo ""
echo "Auth Tokens cannot be retrieved via CLI (they are secrets)."
echo "You have two options:"
echo ""
echo "1. Generate a NEW Auth Token via CLI (will be shown once)"
echo "2. Use an EXISTING Auth Token (you must have it saved)"
echo ""
read -p "Do you want to generate a NEW Auth Token? (yes/no): " -r
echo ""

if [[ $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
    TOKEN_DESCRIPTION="docker-registry-$(date +%Y%m%d-%H%M%S)"
    echo "🔑 Generating new Auth Token: ${TOKEN_DESCRIPTION}"
    echo ""

    AUTH_TOKEN_JSON=$(oci iam auth-token create \
        --user-id "${USER_OCID}" \
        --description "${TOKEN_DESCRIPTION}" \
        --profile "${OCI_PROFILE}" 2>/dev/null)

    if [ $? -eq 0 ]; then
        AUTH_TOKEN=$(echo "${AUTH_TOKEN_JSON}" | jq -r '.data.token')
        echo "✅ Auth Token generated successfully!"
        echo ""
        echo "⚠️  IMPORTANT: This token will NEVER be shown again!"
        echo "   Token: ${AUTH_TOKEN}"
        echo ""
        echo "   Save it securely!"
        echo ""
    else
        echo "❌ Failed to generate Auth Token"
        echo ""
        read -p "Enter your existing Auth Token: " -s AUTH_TOKEN
        echo ""
    fi
else
    echo "📝 Using existing Auth Token"
    echo ""
    read -p "Enter your existing Auth Token: " -s AUTH_TOKEN
    echo ""
    echo ""
fi

# Ask for Portainer admin password
echo "📝 Portainer Configuration"
echo ""
read -p "Enter Portainer admin username [admin]: " PORTAINER_USER
PORTAINER_USER=${PORTAINER_USER:-admin}

read -p "Enter Portainer admin password: " -s PORTAINER_PASS
echo ""
echo ""

# Get manager IP from Terraform or ask user
SCRIPT_DIR_TEMP="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT_TEMP="$(cd "${SCRIPT_DIR_TEMP}/.." && pwd)"
MANAGER_IP=""
if [ -f "${PROJECT_ROOT_TEMP}/terraform/terraform.tfstate" ]; then
    MANAGER_IP=$(grep -A 5 '"public_ip"' "${PROJECT_ROOT_TEMP}/terraform/terraform.tfstate" | head -1 | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+' | head -1)
fi

if [ -z "$MANAGER_IP" ]; then
    echo "Could not detect manager IP from Terraform state"
    read -p "Enter Docker Swarm manager IP address: " MANAGER_IP
fi

# Create the ocir.yml file
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
VARS_DIR="${PROJECT_ROOT}/ansible/vars"
VARS_FILE="${VARS_DIR}/ocir.yml"

mkdir -p "${VARS_DIR}"

echo "📝 Creating configuration file: ${VARS_FILE}"
echo ""

cat > "${VARS_FILE}" <<EOF
# Oracle Container Registry (OCIR) Configuration
# Auto-generated on $(date)
# DO NOT commit this file to Git!

# OCI Region
ocir_region: "${REGION}"

# OCIR Registry URL
ocir_registry: "${REGION}.ocir.io"

# OCI Tenancy Namespace
ocir_tenancy_namespace: "${NAMESPACE}"

# OCI Username
ocir_username: "${USER_NAME}"

# OCI Auth Token
ocir_auth_token: "${AUTH_TOKEN}"

# Portainer configuration
portainer_url: "https://${MANAGER_IP}:9443"
portainer_admin_username: "${PORTAINER_USER}"
portainer_admin_password: "${PORTAINER_PASS}"

# Docker login on nodes
docker_login_enabled: true

# OCIR repository namespace (optional)
ocir_repository_namespace: ""
EOF

chmod 600 "${VARS_FILE}"

echo "✅ Configuration file created successfully!"
echo ""
echo "=========================================="
echo "  Summary"
echo "=========================================="
echo ""
echo "Configuration saved to: ${VARS_FILE}"
echo ""
echo "Registry URL:  ${REGION}.ocir.io"
echo "Username:      ${NAMESPACE}/${USER_NAME}"
echo "Manager IP:    ${MANAGER_IP}"
echo ""
echo "📝 Next steps:"
echo ""
echo "1. Review the configuration file (optional):"
echo "   cat ${VARS_FILE}"
echo ""
echo "2. Run the OCIR configuration:"
echo "   ./configure-ocir.sh"
echo ""
echo "3. Start using OCIR:"
echo "   docker tag myapp:latest ${REGION}.ocir.io/${NAMESPACE}/myapp:latest"
echo "   docker push ${REGION}.ocir.io/${NAMESPACE}/myapp:latest"
echo ""
