[Interface]
PrivateKey = yGsTb7zPVlt8muUT+D5J7Z+j12qfqrncXwW6uYayNEc=
Address = 10.10.0.2/24
DNS = 1.1.1.1

[Peer]
PublicKey = CC0hetlSSE54BcrMsd8zc1b+2g64HTWmBgvSGmSE+Vg=
Endpoint = 130.110.2.182:51820
AllowedIPs = 10.10.0.0/24
PersistentKeepalive = 25
