# Generated by Django 5.0.1 on 2026-02-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScrapingCategoria",
            fields=[
                (
                    "categoria",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorie",
                "db_table": 'events_data"."v_categorie',
                "ordering": ["categoria"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ScrapingLocation",
            fields=[
                (
                    "location_name",
                    models.CharField(max_length=512, primary_key=True, serialize=False),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("count", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "db_table": 'events_data"."v_locations',
                "ordering": ["location_name"],
                "managed": False,
            },
        ),
    ]
