# Generated by Django 5.0.1 on 2026-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoria', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'db_table': 'events_data"."v_categorie',
                'ordering': ['categoria'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'events_data"."v_locations',
                'ordering': ['location_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScrapingWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome portale')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL base')),
                ('spider_name', models.CharField(help_text='Nome del file spider Scrapy (es: in_lombardia)', max_length=100, unique=True, verbose_name='Nome spider')),
                ('cms', models.CharField(choices=[('drupal', 'Drupal'), ('wordpress', 'WordPress'), ('custom', 'Custom'), ('api_rest', 'API REST'), ('api_graphql', 'API GraphQL'), ('liferay', 'Liferay'), ('strapi', 'Strapi'), ('directus', 'Directus'), ('angular_spa', 'Angular SPA'), ('aem', 'Adobe AEM'), ('orchard', 'Orchard CMS'), ('pimcore', 'Pimcore')], default='custom', max_length=20, verbose_name='CMS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('notes', models.TextField(blank=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'db_table': 'scraping_website',
                'ordering': ['name'],
            },
        ),
    ]
