# Generated by Django 5.0.1 on 2026-02-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_create_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingCategory',
            fields=[
                ('categoria', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
                'db_table': 'events_data"."v_categorie',
                'ordering': ['categoria'],
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ScrapingCategoria',
        ),
    ]
