apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-config
  namespace: database
  labels:
    app: backoffice
    component: celery
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_HOST: "postgres.database.svc"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "events"
  POSTGRES_USER: "events"
  OTEL_ENABLED: "false"
  OTEL_SERVICE_NAME: "backoffice-celery"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.monitoring.svc:4317"
