apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: events
  labels:
    app: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
